### PR TITLE
DB schema

### PR DESCRIPTION
**Pull request by Matheus-OAMK**
Added DB schema, subject to change.

Also added some dummy data and test queries. Feel free to add/play around with these. This area is clearly marked on the .SQL file

### CODE REVIEW

**Comment by RepoRover** [comment]
Everything looks very good! The thing worth to mention is statuses "en route to warehouse" and "en route to final destination". I tried to display both versions in current design and found them to be too long. I don't remember the particular need to differentiate those statuses if both mean that parcel is en route.

**Comment by Matheus-OAMK** [comment]
Firstly, all statuses are displayed on the roadmap located in the detailed view of the parcel. Secondly, it's more descriptive for backend users.

**Comment by RepoRover** [comment]
Yesterday I was working on API documentation (you can check it out in api-doc branch) and found status "en route" to be totally useless, in case it doesn't affect on any kind of functionality in backend, so there is no need to differentiate them for a backend user. Status "en route" means that parcel is picked up and on the way to delivery, and no matter where it got picked up from and where it is going.

**Review by RepoRover — APPROVED** [review]
Fuck Java

**Pull request merged**
